name: japanbg
description: "L'appli des BG pour le Japon ğŸŒ"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/group.png
    - assets/cards/1.png
    - assets/cards/2.png
    - assets/cards/3.png
    - assets/cards/4.png
    - assets/cards/5.png
    - assets/cards/6.png
    - assets/cards/7.png
    - assets/cards/8.png
    - assets/cards/9.png
    - assets/cards/10.png
    - assets/cards/11.png
    - assets/cards/12.png
    - assets/cards/13.png
    - assets/cards/14.png
    - assets/cards/15.png
    - assets/cards/16.png
    - assets/cards/17.png
    - assets/cards/18.png
    - assets/cards/19.png
    - assets/cards/20.png
    - assets/cards/21.png
    - assets/cards/22.png
